FROM node:12.13-alpine AS development

RUN mkdir -p /nest
ADD . /nest

WORKDIR /nest

RUN npm install -g @nestjs/cli

RUN npm install --production=false

# Build production files
RUN nest build ws-front-end

# Bundle app source
COPY . .

EXPOSE 3000

CMD ["npm", "run", "start:debug", "ws-front-end"]

FROM node:12.13-alpine as production

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

COPY --from=development /usr/src/app/dist ./dist

CMD ["node", "dist/apps/ws-front-end/main.js"]